import Foundation

// This will be generated by OpenAPI Generator, but we define extension for mapping
extension Components.Schemas.Message {
    func toDomain() -> Message {
        Message(
            id: id,
            conversationId: conversationId,
            senderUserId: senderUserId,
            type: _type == .text ? .text : .system,
            text: text,
            createdAt: createdAt,
            replyToMessageId: replyToMessageId,
            systemEvent: systemEvent?.rawValue
        )
    }
}

extension Components.Schemas.SendMessageRequest {
    static func from(senderUserId: String?, text: String) -> Self {
        Self(
            senderUserId: senderUserId,  // nil means backend will use authenticated user
            text: text,
            replyToMessageId: nil,
            systemEvent: nil
        )
    }
}
