import Foundation

// This will be generated by OpenAPI Generator, but we define extension for mapping
extension Components.Schemas.Message {
    func toDomain() -> Message {
        Message(
            id: id,
            conversationId: conversationId,
            senderUserId: senderUserId,
            type: _type == .text ? .text : .system,
            text: text,
            createdAt: createdAt,
            replyToMessageId: replyToMessageId,
            systemEvent: systemEvent?.rawValue
        )
    }
}

extension Components.Schemas.SendMessageRequest {
    static func from(text: String) -> Self {
        Self(
            text: text,
            replyToMessageId: nil
            // senderUserId and systemEvent removed from spec - backend uses authenticated user
        )
    }
}
