import Foundation

// This will be generated by OpenAPI Generator, but we define extension for mapping
extension Components.Schemas.Reaction {
    func toDomain() -> Reaction {
        Reaction(
            id: id,
            messageId: messageId,
            userId: userId,
            emoji: emoji,
            createdAt: createdAt
        )
    }
}

extension Components.Schemas.ReactionRequest {
    static func from(emoji: String) -> Self {
        Self(
            emoji: emoji
            // userId is no longer in the spec - backend uses authenticated user from cookie
        )
    }
}
