import Foundation

// This will be generated by OpenAPI Generator, but we define extension for mapping
extension Components.Schemas.Reaction {
    func toDomain() -> Reaction {
        Reaction(
            id: id,
            messageId: messageId,
            userId: userId,
            emoji: emoji,
            createdAt: createdAt
        )
    }
}

extension Components.Schemas.ReactionRequest {
    static func from(userId: String?, emoji: String) -> Self {
        Self(
            userId: userId,  // nil means backend will use authenticated user from cookie
            emoji: emoji
        )
    }
}
